### ISSUE TITLE
Quick Start Fail

### ISSUE THREAD

**Issue by xingpengsun** [y-zheng18/GIMO#5]
Hi, I'm trying to run the codebase on Colab and quick start using the demo data using this command: 
`!bash scripts/eval.sh`

Then, I met the following issue can you help me to figure out how to resolve it, thank you: 

`2023-06-20 08:33:25.741889: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.

To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-20 08:33:27.671593: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
loading scene of 2022-01-23-080759
Traceback (most recent call last):
  File "/content/drive/MyDrive/GIMO/eval.py", line 284, in <module>
    evaluator = SMPLX_evalutor(config)
  File "/content/drive/MyDrive/GIMO/eval.py", line 23, in __init__
    self.vposer, _ = load_vposer(self.config.vposer_path, vp_model='snapshot')
  File "/usr/local/lib/python3.10/dist-packages/human_body_prior/tools/model_loader.py", line 56, in load_vposer
    ps, trained_model_fname = expid2model(expr_dir)
  File "/usr/local/lib/python3.10/dist-packages/human_body_prior/tools/model_loader.py", line 31, in expid2model
    best_model_fname = sorted(glob.glob(os.path.join(expr_dir, 'snapshots', '*.pt')), key=os.path.getmtime)[-1]
IndexError: list index out of range`

**Comment by xiaogangpeng** [comment]
I got the same errors!

**Comment by y-zheng18** [comment]
it seems it's related to your vposer installation. Check it [here](https://github.com/nghorbani/human_body_prior/issues/55).

**Comment by xiaogangpeng** [comment]
Hi, the vposer must be cvpr19 version with env of cuda1.0?
